name: s_gridview
description: A lightweight, customizable grid-like Flutter widget with index-based scrolling and tappable scroll indicators
issue_tracker: https://github.com/SoundSliced/s_gridview/issues
repository: https://github.com/SoundSliced/s_gridview
version: 3.0.0
homepage: https://github.com/SoundSliced/s_gridview
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true